[package]
name = "class-schedule-validation"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
class-schedule-domain = { path = "../domain" }
class-schedule-scheduling = { path = "../scheduling" }
serde.workspace = true

[dev-dependencies]
uuid.workspace = true

[lints]
workspace = true

